# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: My own CI / CD Pipeline

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package -DskipTests=true --file pom.xml

    - name: Test with Maven
      run: mvn -B test --batch-mode --no-transfer-progress --file pom.xml

    - name: Report
      uses: dorny/test-reporter@v1
      if: always() 
      with:
        name: JEST Tests            
        path: target/surfire-reports/*.xml 
        reporter: java-junit        
        fail-on-error: true

    - name: Upload JAR artifact
      uses: actions/upload-artifact@v2
      if: success()
      with:
        name: fraction
        path: target/*.jar
